//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Project3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchFileTBL
    {
        public int ID { get; set; }
        public string FILE_NAME { get; set; }
        public string DIR_NAME { get; set; }
        public string RESULT { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
